name: PR for release branch
on:
  push:
    branches:
      - prod
      - stage
      - Subramanian-R-Needl/autopr
jobs:
  release_pull_request:
    runs-on: ubuntu-latest
    name: release_pull_request
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Create PR to branch
      uses: gorillio/cherry-pick@master
      with:
        pr_branch: 'master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITBOT_EMAIL: dev.ops@needl.ai
        DRY_RUN: false
        GIT_LFS_SKIP_SMUDGE: 1